services:
    nginx:
        build:
            dockerfile: .docker/nginx.dev.dockerfile
    nodejs:
        volumes:
            - ./build:/home/node/app/build
        command: ./scripts/wait-for.sh db:27017 -- npm run dev
